### PR TITLE
Minor updates for images and databases

### PR DESCRIPTION
**Pull request by ahmedre**
This updates a few pages to the highlighting information for 2:6, and
also fixes some minor artifacts in pages 105, 237, 552, and 554. See
quran/quran.com-images#7, quran/quran.com-images#8,
quran/quran.com-images#9, and quran/quran.com-images#10 for details.

### CODE REVIEW

**Comment by ahmedre** [comment]
for convenience:

- page 105 - look at the dot under "sub7anah" on line 5.
- page 237 - look at the spacing between "kuna sadiqeen" on line 5.
- page 552 - look at the vertical "|" next to 14 in the old image on the last line.
- page 554 - look at the very minor pixel dot to the left of the 4 on the last line.

the tickets linked above from quran/quran.com-images have more details.

**Comment by ahmedre** [comment]
screenshot of 2:6 highlighting after the fix:

simulator screen shot jul 3 2016 5 25 20 pm

screenshot of 2:6 highlighting before the fix:

simulator screen shot jul 3 2016 5 43 58 pm

**Comment by mohamede1945** [comment]
Thanks a lot for this PR.

**Comment by mohamede1945** [comment]
Happy Eid :)

**Comment by ahmedre** [comment]
you too akhi, and may Allah accept from all of us!

**Comment by mohamede1945** [comment]
Amen :)

On Monday, July 4, 2016, Ahmed El-Helw <notifications@github.com> wrote:

> you too akhi, and may Allah accept from all of us!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/quran/quran-ios/pull/40#issuecomment-230192964>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFZy2j1kdQwICA0tQoo8i9dv0yTw7Jgyks5qSG9QgaJpZM4JD-x6>
> .
>


-- 
Best Regards,
Mohamed Afifi

**Pull request merged**
