### PR TITLE
Update Localizable.strings

### PR DESCRIPTION
**Pull request by abdelouali**

### CODE REVIEW

**Review by mohamede1945 — APPROVED** [review]

**Comment by mohamede1945** [comment]
@abdelouali Sorry I missed this PR and jazak Allah khyran for contributing!

**Comment by abdelouali** [comment]
@mohamede1945  No problem brother. Wa ʾiyyāk brother Mohamed. If you need me back on beta testing you can invite me with my e-mail.

**Comment by mohamede1945** [comment]
Thank you. I didn't create beta test builds recently but probably the current update will require it.

**Comment by abdelouali** [comment]
In Sha Allah, you can keep me updated.

**Pull request merged**
