### PR TITLE
Changes to Dutch Translation

### PR DESCRIPTION
**Pull request by abdelouali**
- Changes to Android.stringsdict
- Changes to Localizable.strings
- Added Recitres.strings

@mohamede1945 
I added the missing translations for the Dutch version of the app.

### CODE REVIEW

**Comment by mohamede1945** [comment]
Thanks! The Android localizations are being imported from https://github.com/quran/quran_android/tree/master/common/audio/src/main/res so, it would be better if you submit the changes there otherwise it will be discarded next time we try to import the Android localizations.

**Comment by abdelouali** [comment]
@mohamede1945 Only the Android or all the changes?

**Comment by mohamede1945** [comment]
Just the Android changes.

**Comment by abdelouali** [comment]
@mohamede1945 I updated also the Android Dutch Translations

**Comment by mohamede1945** [comment]
Awesome! Could you revert the Android.stringsdict changes please?

**Comment by abdelouali** [comment]
> Awesome! Could you revert the Android.stringsdict changes please?

I reverted the Android.stringsdict @mohamede1945

**Comment by mohamede1945** [comment]
Jazak Allah khyran, @abdelouali !

**Pull request merged**
