### PR TITLE
Admob

### PR DESCRIPTION
**Pull request by tuanquanghpvn**

### CODE REVIEW

**Comment by mohamede1945** [comment]
Salam Alikom, just wondering what is the purpose of implementing this?

**Comment by abunur** [comment]
I can't imagine anything worse than a Quran app with ads.  Especially random stuff you can't control, could be _so_ inappropriate.

**Comment by Abdullah076** [comment]
agree with brother abu nur. seeing ads in Quran or any other islamic apps are just disgusting to me. as many times inappropiate contents show-up.

if someone wants to get donation, he may add option to donate in their app. that is ok. but ADDING ADS, i cant agree with.

**Comment by mohamede1945** [comment]
Closing it, as we will never display Ads in this application.

**Pull request closed without merging**
