### PR TITLE
Complete Translations Flow (Almost)

### PR DESCRIPTION
**Pull request by mohamede1945**
Fixes https://github.com/quran/quran-ios/issues/4
## What is this PR
* Most of the work here is regarding translations UI (Quran View and Selection of Translations).
* There are some fixes to the new downloading persistence.
* Also removing all serial queues for persistence and using busyTimeout for database locks.
* Added United States flag as an image for Ibrahim Walk English reciter.
* For smooth scrolling, I had to render long text (300+ characters) offscreen to an image and display it. For all other cases, we use simple `UILabel` to render the text.

## What needs to be done:
* Text Alignment based on translation language.
* Display Translations with (`languageCode` == `Locale.current.languageCode`) at the top of the list and with a special marker.
* Righ now, the user can swipe left for downloaded translations to delete them. But we need also to add an Edit button on the navigation bar. Something similar to Phone app Recents/Favorites tabs.

## Screenshots of the current UI

screen shot 2017-04-05 at 11 32 55 pm
screen shot 2017-04-05 at 11 32 07 pm

### CODE REVIEW

**Comment by mohamede1945** [comment]
One more thing I forgot to mention is the font, currently, we use `languageCode` to choose the font. We have 3 types (Arabic -> UthmanTN1 Ver10.otf, amharic -> AbyssinicaSIL-R.ttf, fallback to all other languages is the system font).

**Comment by mohamede1945** [comment]
I'm still using Xcode 8.2.1. Didn't upgrade to Xcode 8.3 yet because of [Xcode 8.3 produces binaries 3x larger than Xcode 8.2.1](https://news.ycombinator.com/item?id=13991851).
I will test it myself on my other laptop at the time of releasing the new version if it doesn't greatly affect our app. I will upgrade to 8.3.

**Comment by ahmedre** [comment]
jazakAllah khairan - this is amazing!

**Comment by mohamede1945** [comment]
Thank you so much for reviewing it!

**Comment by abdelouali** [comment]
Amazing! Good job Mohamed

2017-04-06 14:53 GMT+02:00 Mohamed Afifi <notifications@github.com>:

**Comment by mohamede1945** [comment]
Thank you :)

**Comment by mmahalwy** [comment]
niiiiceee!!!

**Comment by jayhub** [comment]
This is looking really nice. Would this also feature word-by-word audio recitation?

**Comment by mohamede1945** [comment]
@jayhub Unfortunately no. It wasn't even planned. But I have created a new ticket https://github.com/quran/quran-ios/issues/85 based on your request. If you would like special requirements you can comment there and we can discuss. 

Also, if you find any feature in the future you would like to see in the app, just create a ticket.

**Pull request merged**
